name: Build site
on: [push, pull_request]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: build jekyll
        uses: jerryjvl/jekyll-build-action@v1
      - name: Deploy to neocities
        uses: bcomnes/deploy-to-neocities@v1
        if: ${{ success() && github.ref == 'refs/heads/main' }}
        with:
          api_token: ${{ secrets.NEOCITIES_API_KEY }}
          dist_dir: _site
          cleanup: true
      - name: Deploy to Neocities fallback
        if: ${{ steps.deploy.outcome == 'failure' && github.ref == 'refs/heads/main' }}
        uses: jonchang/deploy-neocities@master
        with:
          key: ${{ secrets.NEOCITIES_API_KEY }}
          dir: _site
          clean: true
